# Generated by Django 2.1.7 on 2021-06-24 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20210603_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='url',
            field=models.TextField(blank=True, default='/Users/shahargino/Projects/sea_analytics/media', null=True, verbose_name='Relative URL Path to GPX file'),
        ),
        migrations.AlterField(
            model_name='media',
            name='url',
            field=models.TextField(blank=True, default='/Users/shahargino/Projects/sea_analytics/media', null=True, verbose_name='Path to media files'),
        ),
    ]
