# Generated by Django 2.1.7 on 2021-07-11 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_media_favorite_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Athlete'), (2, 'Coach')], null=True, verbose_name='User Type'),
        ),
    ]
