# Generated by Django 2.1.7 on 2021-11-08 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20210711_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='training_appendices',
            field=models.TextField(blank=True, default='n/a', null=True, verbose_name='Appendices'),
        ),
    ]
