# Generated by Django 2.1.7 on 2021-11-16 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20211108_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='distance_loss_en',
            field=models.BooleanField(default=False),
        ),
    ]
