# Generated by Django 2.1.7 on 2021-11-19 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_profile_distance_loss_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='training_distloss_n_buffers',
            field=models.PositiveSmallIntegerField(blank=True, default='10', null=True, verbose_name='Training Distance Loss Buffer'),
        ),
        migrations.AddField(
            model_name='profile',
            name='training_distloss_n_segments',
            field=models.PositiveSmallIntegerField(blank=True, default='3', null=True, verbose_name='Training Distance Loss Segments'),
        ),
        migrations.AddField(
            model_name='profile',
            name='training_distloss_tack_width_max',
            field=models.PositiveSmallIntegerField(blank=True, default='150', null=True, verbose_name='Training Distance Loss Tack Max Width'),
        ),
        migrations.AddField(
            model_name='profile',
            name='training_distloss_tack_width_min',
            field=models.PositiveSmallIntegerField(blank=True, default='70', null=True, verbose_name='Training Distance Loss Tack Min Width'),
        ),
    ]
