# Generated by Django 2.1.7 on 2021-11-20 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20211119_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='training_air_temp_override',
            field=models.CharField(blank=True, default='auto', max_length=250, verbose_name='Air Temp override'),
        ),
        migrations.AddField(
            model_name='training',
            name='training_current_direction_override',
            field=models.CharField(blank=True, default='auto', max_length=250, verbose_name='Current Direction'),
        ),
        migrations.AddField(
            model_name='training',
            name='training_current_speed_override',
            field=models.CharField(blank=True, default='auto', max_length=250, verbose_name='Current Speed override'),
        ),
        migrations.AddField(
            model_name='training',
            name='training_type_override',
            field=models.CharField(blank=True, default='auto', max_length=250, verbose_name='Training Type override'),
        ),
        migrations.AddField(
            model_name='training',
            name='training_wave_direction_override',
            field=models.CharField(blank=True, default='auto', max_length=250, verbose_name='Wave Direction override'),
        ),
        migrations.AddField(
            model_name='training',
            name='training_wave_height_override',
            field=models.CharField(blank=True, default='auto', max_length=250, verbose_name='Wave Height override'),
        ),
        migrations.AddField(
            model_name='training',
            name='training_wave_period_override',
            field=models.CharField(blank=True, default='auto', max_length=250, verbose_name='Wave Period override'),
        ),
        migrations.AddField(
            model_name='training',
            name='training_wind_direction_override',
            field=models.CharField(blank=True, default='auto', max_length=250, verbose_name='Wind Direction override'),
        ),
        migrations.AddField(
            model_name='training',
            name='training_wind_gust_override',
            field=models.CharField(blank=True, default='auto', max_length=250, verbose_name='Wind Gust override'),
        ),
        migrations.AddField(
            model_name='training',
            name='training_wind_speed_override',
            field=models.CharField(blank=True, default='auto', max_length=250, verbose_name='Wind Speed override'),
        ),
    ]
