# Generated by Django 2.1.7 on 2021-11-22 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_auto_20211120_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='training_merged_marks',
            field=models.TextField(blank=True, default='n/a', null=True, verbose_name='Merged Marks'),
        ),
    ]
