# Generated by Django 2.1.7 on 2021-11-23 06:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_training_training_merged_marks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='org_name',
            field=models.CharField(blank=True, help_text='Organization (Club) Name', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='trainers',
            field=models.ManyToManyField(blank=True, default=None, limit_choices_to={'profile__type__gte': '2'}, related_name='Trainers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Athlete'), (2, 'Coach'), (3, 'Senior Coach'), (4, 'Club Staff')], null=True, verbose_name='User Type'),
        ),
    ]
