# Generated by Django 2.1.7 on 2021-11-28 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_auto_20211123_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='org_name',
            field=models.CharField(blank=True, default='NA', help_text='Organization (Club) Name', max_length=100, null=True),
        ),
    ]
