# Generated by Django 2.1.7 on 2021-12-25 12:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_auto_20211201_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='training_id',
            field=models.CharField(blank=True, max_length=250, validators=[django.core.validators.RegexValidator(message='Training ID shall not comprise any dots in its name', regex='^[^.]+$')], verbose_name='Training ID'),
        ),
    ]
