# Generated by Django 2.1.7 on 2021-12-26 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_auto_20211225_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='training_distloss_tack_width_max',
            field=models.PositiveSmallIntegerField(blank=True, default=150, null=True, verbose_name='Training Distance Loss Tack Max Width'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='training_distloss_tack_width_min',
            field=models.PositiveSmallIntegerField(blank=True, default=70, null=True, verbose_name='Training Distance Loss Tack Min Width'),
        ),
    ]
