# Generated by Django 2.1.7 on 2021-12-29 11:57

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0017_auto_20211226_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='originator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='training',
            name='training_id',
            field=models.CharField(blank=True, max_length=250, validators=[django.core.validators.RegexValidator(message='Training ID shall only comprise letters and numbers', regex='^[A-Za-z0-9]+$')], verbose_name='Training ID'),
        ),
    ]
