# Generated by Django 2.1.7 on 2022-02-18 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_auto_20211229_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='training_distloss_disable',
            field=models.BooleanField(default=False),
        ),
    ]
