# Generated by Django 2.1.7 on 2022-03-02 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_profile_training_distloss_disable'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='training_trainee_min_speed_thr',
            field=models.CharField(blank=True, default='0', max_length=100, null=True, verbose_name='Training Minimal Speed Threshold'),
        ),
    ]
