# Generated by Django 2.1.7 on 2022-03-13 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_profile_training_trainee_min_speed_thr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='training_trainee_time_hours_offset',
            field=models.SmallIntegerField(blank=True, default=2, null=True, verbose_name='Training Athlete Hours Offset'),
        ),
    ]
