# Generated by Django 2.1.7 on 2022-04-05 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_auto_20220313_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Athlete'), (2, 'Coach'), (3, 'Senior Coach'), (4, 'Club Staff'), (5, 'Clinic Athlete')], null=True, verbose_name='User Type'),
        ),
    ]
