# Generated by Django 2.1.7 on 2022-04-06 10:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0022_auto_20220405_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='trainers',
            field=models.ManyToManyField(blank=True, default=None, limit_choices_to={'profile__type__gte': '3'}, related_name='Trainers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Athlete'), (2, 'Clinic Athlete'), (3, 'Coach'), (4, 'Senior Coach'), (5, 'Club Staff')], null=True, verbose_name='User Type'),
        ),
    ]
