# Generated by Django 2.1.7 on 2022-05-23 11:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0023_auto_20220406_1330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='training_trainee_min_speed_thr',
        ),
        migrations.AddField(
            model_name='profile',
            name='training_trainee_speed_thr',
            field=models.CharField(blank=True, default='0;100', max_length=100, null=True, verbose_name='Training Min/Max Speed Threshold'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='trainees',
            field=models.ManyToManyField(blank=True, default=None, limit_choices_to={'profile__type__in': ['1', '2']}, related_name='Trainees', to=settings.AUTH_USER_MODEL),
        ),
    ]
