# Generated by Django 2.1.7 on 2022-06-01 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0024_auto_20220523_1435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='training_distloss_disable',
        ),
        migrations.AddField(
            model_name='profile',
            name='training_distloss_mode',
            field=models.SmallIntegerField(blank=True, default=1, null=True, verbose_name='Training Distance Loss Mode'),
        ),
    ]
